polls/engine/urls.py
from django.urls import path
from . import views

# Use to separate urls from different apps in a project
app_name = 'polls'

urlpatterns = [
    # /polls/
    path('', views.IndexView.as_view(), name='index'),

    # /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('engine.urls')),
    path('admin/', admin.site.urls),
]

polls/engine/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    # max_length: User defined
    question = models.CharField(max_length=300)

    # Parameter passed is an optional positional argument
    # Can be used as a human-readable name representation on a field
    # https://stackoverflow.com/questions/27077125/what-is-the-meaning-of-string-argument-in-django-models-field
    pub_date = models.DateTimeField('Date Published')

    # __str__ provides meaningful string representation used in Django's automatically-generated form
    def __str__(self):
        return self.question

    # Django model classes also allows to include custom methods used in querying objects
    # This method returns a boolean if object was created recently (within the day as seen in the parameter)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) < self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = "Published Recently?"


class Choice(models.Model):
    # Provides reference to the Question object
    # Django automatically creates related object set with respect to the question object
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/engine/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'questions'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "No choice was selected"
        })

    else:
        selected.votes += 1
        selected.save()

        # Returning HttpResponseRedirect prevents data from being posted twice
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/engine/templates/polls/detail.html
<a href="{% url 'polls:index' %}">Back To Questions</a>
<h2>{{ question.question }}</h2>

{% if error_message %}
    <p>
        <strong>
            {{  error_message }}
        </strong>
    </p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

polls/engine/templates/polls/index.html
{% if questions %}
    <ul>
        {% for question in questions %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question }}</a></li>
        {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/engine/templates/polls/results.html
<a href="{% url 'polls:index' %}">Back To Questions</a>
<h2>{{ question.question }}</h2>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>